[package]
name = "x"
version = "0.1.0"
edition = "2024"

[dependencies]
core = { path = "../core" }
bytes = "1.11.0"

tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["fmt", "env-filter"] }